# Generated by Django 5.0 on 2024-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_id_alter_customer_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
